version: '3'
services:
  app:
    container_name: cvapi
    build:
      context: ./go-app
      dockerfile: Dockerfile
    environment:
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: on-failure
    networks:
      - gonet
  db:
    container_name: db
    image: postgres:latest
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - gonet

networks:
  gonet:
    driver: bridge